name: Samairah
favicon: null
layout_spectrum: 1
typography_spectrum: 0.45584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4932687042746693
  lightness: 0.3456611337605864
  saturation: 0.3342604509089142
  rhythmicContrast: 0
purpose: []
